# Generated by Django 5.0.4 on 2024-04-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foretag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_stores', models.ManyToManyField(to='foretag.store')),
            ],
            options={
                'verbose_name': 'MobileUser',
                'verbose_name_plural': 'MobileUsers',
            },
        ),
    ]
