# Generated by Django 5.0.4 on 2024-05-02 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foretag', '0002_delete_reservation'),
        ('user_api', '0002_mobileuser_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileuser',
            name='favorite_stores',
            field=models.ManyToManyField(blank=True, to='foretag.store'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_claimed', models.PositiveSmallIntegerField()),
                ('claim_time', models.DateTimeField(auto_now_add=True)),
                ('paid_for', models.BooleanField(default=False)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foretag.ad')),
                ('claimer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.mobileuser')),
            ],
        ),
    ]
