# Generated by Django 5.0.4 on 2024-05-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_alter_mobileuser_favorite_stores'),
        ('user_api', '0004_order_remove_reservation_paid_for_and_more'),
    ]

    operations = [
    ]
