# Generated by Django 4.2.11 on 2024-03-27 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=250)),
                ('available', models.PositiveSmallIntegerField(default=1)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('until', models.DateTimeField(auto_now_add=True)),
                ('old_price', models.PositiveIntegerField(default=0)),
                ('new_price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug_name', models.SlugField()),
                ('credentials', models.CharField(default='Not connected', max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('postal_city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimer', models.CharField(default='not claimed yet!', max_length=100)),
                ('claim_time', models.DateTimeField(auto_now_add=True)),
                ('paid_for', models.BooleanField(default=False)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foretag.ad')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foretag.store'),
        ),
    ]
