# Generated by Django 4.2.11 on 2024-04-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foretag', '0002_ad_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, default='error.png', null=True, upload_to='media')),
            ],
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, default='error.png', null=True, upload_to='media'),
        ),
    ]
