# Generated by Django 5.0.4 on 2024-05-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foretag', '0002_delete_reservation'),
        ('foretag', '0003_alter_store_credentials'),
    ]

    operations = [
    ]
