# Generated by Django 5.0.4 on 2024-05-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foretag', '0004_merge_20240507_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.CharField(default='Annat', max_length=40),
        ),
    ]
