# Generated by Django 5.0.4 on 2024-05-13 11:58

import foretag.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foretag', '0005_ad_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='banner',
            field=models.CharField(default=foretag.models.random_store_banner, max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='thumbnail',
            field=models.CharField(default=foretag.models.random_store_thumbnail, max_length=100),
        ),
    ]
