# Generated by Django 4.1 on 2024-05-15 11:06

from django.db import migrations, models
import foretag.models


class Migration(migrations.Migration):

    dependencies = [
        ("foretag", "0007_ad_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="thumbnail",
            field=models.CharField(
                default=foretag.models.random_product_thumbnail, max_length=10000
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="banner",
            field=models.CharField(
                default=foretag.models.random_store_banner, max_length=10000
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="thumbnail",
            field=models.CharField(
                default=foretag.models.random_store_thumbnail, max_length=10000
            ),
        ),
    ]
